sudo: false
language: python
python:
  - "3.6"
install:
  - pip install tox-travis
  - python setup.py build
  - python setup.py install
script:
  - tox
notifications:
  email:
    recipients:
    - brandon@fortifyadmin.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: nMIGJAoGBALeFvpaS4szqW9jo3uH3kaS2YJZSyghvokomKuiPIBr8mnO6BNm6C5sJ\nDKX7ihhJdKUA/MpEFCiObj5ZPiXcV7gHlyVN2FCP5ucFLHtasa3j6nCH5lvdLxAw\nAbPKq8PPCq8rurmFWBLuuCWXR0VW2OG1+Oo4b9U1d5ywST7hpvOrAgMBAAE=
  file_glob: true
  file:
  - dist/*.zip
  skip_cleanup: true
  on:
    repo: fortifyadmin/fortifyapi
    branch: master
    tags: true
after_success:
  - coveralls
after_failure: "cat /home/travis/build/target/fortifyapi/.tox/py27/log/py27-2.log"
